PyGenius/PyGenius/urls.py
from django.contrib import admin
from .initcmds import init_db
from django.urls import path, include, re_path
from .views import *
from gestione.views import ListaCanzoni

urlpatterns = [
    re_path(r'^$|^\/$|^home\/$', ListaCanzoni.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('gestione/', include('gestione.urls')),
]
#init_db()

PyGenius/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', CreaUtenteEditor.as_view(), name='register'),
    path('register-artist/', CreaUtenteArtista.as_view(), name='register-artist')
]

PyGenius/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

PyGenius/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group


class CreaEditorForm(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Editor")
        g.user_set.add(user)
        return user

class CreaArtistaForm(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit)
        g = Group.objects.get(name="Artisti")
        g.user_set.add(user)
        g = Group.objects.get(name="Editor")
        g.user_set.add(user)
        return user

PyGenius/accounts/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.views.generic.edit import CreateView
# Create your views here.

class CreaUtenteEditor(CreateView):
    form_class = CreaEditorForm
    template_name = 'accounts/crea_editor.html'
    success_url = reverse_lazy('accounts:login')

class CreaUtenteArtista(CreateView):
    form_class = CreaArtistaForm
    template_name = 'accounts/crea_artista.html'
    success_url = reverse_lazy('accounts:login')

PyGenius/accounts/templates/accounts/crea_artista.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Creazione Artista {% endblock %}

{% block header1 %}
  Pagina di Registrazione per artisti
{% endblock %}

{% block content %}

<form method="post"> {% csrf_token %}

  {{form | crispy}}

  <input type="submit" class="btn btn-success" value="Registrati ora!">

  </form>
<br>
<div>
  <p> <a href="{% url 'accounts:register' %}">Non sei un artista?</a></p>
</div>

{% endblock %}

{% block footer %} {% endblock %}

PyGenius/accounts/templates/accounts/crea_editor.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block title %} Creazione Editor {% endblock %}

{% block header1 %}
  Pagina di Registrazione
{% endblock %}

{% block content %}

<form method="post"> {% csrf_token %}

  {{form | crispy}}

  <input type="submit" class="btn btn-success" value="Registrati ora!">

  </form>
<br>
<div>
  <p> <a href="{% url 'accounts:register-artist' %}">Sei un artista?</a></p>
</div>

{% endblock %}

{% block footer %} {% endblock %}