PyGenius/PyGenius/urls.py
from django.contrib import admin
from .initcmds import init_db
from django.urls import path, include, re_path
from .views import *
from gestione.views import ListaCanzoni

urlpatterns = [
    re_path(r'^$|^\/$|^home\/$', ListaCanzoni.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('gestione/', include('gestione.urls')),
]
#init_db()

PyGenius/gestione/urls.py
from django.urls import path, include, re_path
from .views import *

app_name='gestione'

urlpatterns = [
    path('creacanzone/', CreaCanzone.as_view(), name='creacanzone'),
    path('listacanzoni/', ListaCanzoni.as_view(), name='listacanzoni'),
    path('listacanzoni/<pk>/', ListaCanzoniArtista.as_view(), name='listacanzoni'),
    path('dettagliacanzone/<pk>/', DettagliaCanzone.as_view(), name='dettagliacanzone'),
    path('eliminacanzone/<pk>/', EliminaCanzone.as_view(), name='eliminacanzone'),
    path('creacontributo/<pk>/', CreaContributo.as_view(), name='creacontributo'),
    path('eliminacontributo/<pk>/', EliminaContributo.as_view(), name='eliminacontributo'),
    path('creaalbum/', CreaAlbum.as_view(), name='creaalbum'),
    path('listaalbum/', ListaAlbum.as_view(), name='listaalbum'),
    path('dettaglialbum/<pk>/', DettagliaAlbum.as_view(), name='dettagliaalbum'),
    path('eliminaalbum/<pk>/', EliminaAlbum.as_view(), name='eliminaalbum'),
    path('ricerca/', RisultatiRicerca, name='ricerca'),
]

PyGenius/gestione/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from .models import *

class CreaCanzoneForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id='creacanzone_crispy_form'
    helper.form_method = 'POST'
    style_string = 'background-color:#3C1B37;border-top:10px;border-left:10px;border-color:#1A1018;color:#E4DFE2'
    helper.add_input(Submit('submit', 'Aggiungi Canzone', style=style_string))
    helper.layout = Layout(
        Field('titolo', css_class='text-center', style=style_string),
        HTML("<br>"),
        Field('durata', placeholder='00:00', css_class='text-center',style=style_string),
        HTML("<br>"),
        Field('data_pub', css_class='text-center',style=style_string),
        HTML("<br>"),
        Field('testo', css_class='text-center',style=style_string),
        HTML("<br>"),
        Field('cover', css_class='text-center',style='background-color:#000000'),
        HTML("<div style='color:#BBBBBB'>Immagine di copertina non obbligatoria(500x500) </div> <br>"),
        Field('album', css_class='text-center', style=style_string),
        HTML("<br>")
            )

    def clean(self):
        if self.cleaned_data['data_pub'] > datetime.date.today():
            self.add_error('data_pub', 'La data inserita è successiva alla data odierna.')
        return self.cleaned_data

    class Meta:
        model = Canzone
        fields =['titolo','durata','data_pub','testo','cover','album']
        widgets = {
            'data_pub' : forms.DateInput(attrs={'type':'date'}),
            'cover' : forms.FileInput(attrs={'style':'background-color:#3C1B37;border-top:10px;border-left:10px;border-color:#1A1018;color:#E4DFE2'}),

        }

class CreaContributoForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id='creacontributo_crispy_form'
    helper.form_method = 'POST'
    style_string = 'background-color:#3C1B37;border-top:10px;border-left:10px;border-color:#1A1018;color:#E4DFE2'
    helper.add_input(Submit('submit', 'Aggiungi Contributo', style=style_string))
    helper.layout = Layout(
        Field('testo', css_class='text-center', style=style_string),
        HTML("<br>"),
            )
    class Meta:
        model = Contributo
        fields =['testo']

class CreaAlbumForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id='creaalbum_crispy_form'
    helper.form_method = 'POST'
    style_string = 'background-color:#3C1B37;border-top:10px;border-left:10px;border-color:#1A1018;color:#E4DFE2'
    helper.add_input(Submit('submit', 'Aggiungi Album', style=style_string))
    helper.layout = Layout(
        Field('titolo', css_class='text-center', style=style_string),
        HTML("<br>"),
        Field('data_pub', css_class='text-center', style=style_string),
        HTML("<br>"),
        Field('cover', css_class='text-center', style=style_string),
        HTML("<br>"),
            )

    def clean(self):
        if self.cleaned_data['data_pub'] > datetime.date.today():
            self.add_error('data_pub', 'La data inserita è successiva alla data odierna.')
        return self.cleaned_data

    class Meta:
        model = Album
        fields = ['titolo', 'data_pub', 'cover']
        widgets = {
            'data_pub': forms.DateInput(attrs={'type': 'date'}),
            'cover': forms.FileInput(attrs={
                'style': 'background-color:#3C1B37;border-top:10px;border-left:10px;border-color:#1A1018;color:#E4DFE2'}),
        }

PyGenius/gestione/views.py
import datetime

from braces.views import GroupRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView

from .forms import *

BASE = Path(__file__).resolve().parent.parent




class CreaCanzone(GroupRequiredMixin,CreateView):
    group_required = ["Artisti"]
    title = "Aggiungi una canzone alle tue pubblicazioni"
    form_class = CreaCanzoneForm
    template_name = "gestione/creacanzone.html"

    def get_success_url(self):
        return reverse_lazy('gestione:dettagliacanzone', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        artista = self.request.user
        form.instance.autore = artista
        log_path = os.path.join(BASE, 'static','media','logs')
        if not os.path.isdir(log_path):
            os.mkdir(log_path)
        open(os.path.join(BASE, 'static','media','logs', f'file_{form.instance.titolo.replace(" ","_")+artista.username.replace(" ", "_")}'),'ab')
        form.instance.file_visite = os.path.join(log_path, f'file_{form.instance.titolo.replace(" ","_")+artista.username.replace(" ", "_")}')
        form.instance.titolo_autore = form.instance.titolo + artista.username

        q = Canzone.objects.filter(titolo_autore = form.instance.titolo_autore)
        if len(q)>0:
            return HttpResponseRedirect(reverse_lazy('gestione:creacanzone') + '?error=double')
            #raise forms.ValidationError('Esiste già una canzone con questo titolo e artista', code='invalid')
        return super(CreaCanzone, self).form_valid(form)


class CreaContributo(GroupRequiredMixin,CreateView):
    group_required = ["Editor"]
    title = "Aggiungi un contributo"
    form_class = CreaContributoForm
    template_name = "gestione/creacontributo.html"

    def get_success_url(self):
        return reverse_lazy('gestione:dettagliacanzone',kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        editor = self.request.user
        canzone = Canzone.objects.filter(titolo_autore=self.kwargs['pk'])[0]
        data_post = datetime.date.today()
        form.instance.canzone = canzone
        form.instance.data_post = data_post
        form.instance.editor = editor

        return super(CreaContributo, self).form_valid(form)



    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['editor'] = self.kwargs['pk']
        return context

class ListaCanzoni(ListView):
    model = Canzone
    template_name = 'gestione/listacanzoni.html'
    queryset = Canzone.objects.order_by('-popolarità')[:15]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'Canzoni'
        return context

class ListaCanzoniArtista(ListView):
    model = Canzone
    template_name = 'gestione/listacanzoni.html'
    ordering = ['-visite']

    def get_queryset(self):
        arg = self.kwargs['pk']
        qs=self.model.objects.filter(autore=arg)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data()
        context['title'] = 'Canzoni'
        return context

class DettagliaCanzone(DetailView):
    model = Canzone
    template_name = 'gestione/dettagliacanzone.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data()
        context['lista_contributi_star'] = Contributo.objects.filter(canzone=self.kwargs['pk']).filter(ha_star=True).order_by('-upvotes')
        context['lista_contributi_non_star'] = Contributo.objects.filter(canzone=self.kwargs['pk']).filter(ha_star=False).order_by('-upvotes')

        ip = self.request.META['REMOTE_ADDR'].split(sep='.')
        guest = ''
        for num in ip:
            guest+=num
        guest = int(guest)

        context['guest'] = guest


        #print(context['lista_contributi'])
        #print(context['lista_contributi'][0].downvote)
        return context

class EliminaCanzone(GroupRequiredMixin,DeleteView):
    group_required = ["Artisti"]
    model = Canzone
    def get_success_url(self):

        return reverse_lazy('gestione:listacanzoni')+f'?canzoneeliminato={self.object.titolo}'


class CreaAlbum(GroupRequiredMixin,CreateView):
    group_required = ["Editor"]
    model = Album
    form_class = CreaAlbumForm
    template_name = 'gestione/creaalbum.html'

    def get_success_url(self):
        return reverse_lazy('gestione:dettagliaalbum',kwargs={'pk':self.object.pk})

    def form_valid(self, form):
        artista = self.request.user
        form.instance.autore = artista
        form.instance.titolo_autore = form.instance.titolo + artista.username
        q = Album.objects.filter(titolo_autore=form.instance.titolo_autore)
        if len(q) > 0:
            return HttpResponseRedirect(reverse_lazy('gestione:creaalbum')+'?error=double')
            #raise forms.ValidationError('Esiste già un album con questo autore e titolo')
        return super(CreaAlbum, self).form_valid(form)


class ListaAlbum(ListView):
    model = Album
    template_name = 'gestione/listaalbum.html'
    queryset = Album.objects.order_by('-popolarità')[:15]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'Albums'
        return context


class DettagliaAlbum(DetailView):
    model = Album
    template_name = 'gestione/dettagliaalbum.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data()
        context['lista_canzoni'] = Canzone.objects.filter(album=self.kwargs['pk'])

        return context


class EliminaAlbum(GroupRequiredMixin,DeleteView):
    group_required = ["Artisti"]
    model = Album

    def get_success_url(self):
        return reverse_lazy('gestione:listaalbum') + f'?albumeliminato={self.object.titolo}'

class EliminaContributo(GroupRequiredMixin,DeleteView):
    group_required = ["Editor"]
    model = Contributo

    def get_success_url(self):
        return reverse_lazy('gestione:listacanzoni') + f'?contributoeliminato={self.object.testo}'

def RisultatiRicerca(request):
        search = request.GET['q']
        model = request.GET['model']

        if model=='Artisti':
            artista = User.objects.filter(username=search)

            if len(artista) == 1:

                return HttpResponseRedirect(f"{reverse_lazy('gestione:listacanzoni')}{artista[0].pk}")
            else :
                return HttpResponseRedirect(reverse_lazy('gestione:listacanzoni')+'?search=none')
        if model == 'Canzoni':
            canzone = Canzone.objects.filter(titolo=search)


            if len(canzone) > 0 :

                return HttpResponse(render_to_string("gestione/listacanzoni.html",context={'object_list': canzone, 'user':request.user}))
            else:
                return HttpResponseRedirect(reverse_lazy('gestione:listacanzoni') + '?search=none')
        if model == 'Album':
            album = Album.objects.filter(titolo=search)


            if len(album) > 0:

                return HttpResponse(render_to_string("gestione/listaalbum.html", context={'object_list': album,'user':request.user}))
            else:
                return HttpResponseRedirect(reverse_lazy('gestione:listacanzoni') + '?search=none')

PyGenius/gestione/templates/gestione/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Album eliminata{%endblock%}

{% block header1 %}
    <center>
        Vuoi Eliminare l'album {{object.titolo|capfirst}}?
    <br>
    <a style="font-size:30px;color:black;text-decoration:underline;" href="{%url 'gestione:listaalbum' %}">Torna alla lista di album</a>
{% endblock %}

{% load static %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p style="font-size:45px;text-align:center">L'AZIONE NON È ANNULLABILE</p>
        {{ form }}
        <br>
        <center><input style="font-size:45px" type="submit" value="Conferma"></center>

    </form>
    </center>
{% endblock %}

PyGenius/gestione/templates/gestione/canzone_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Canzone eliminata{%endblock%}

{% block header1 %}
    <center>
        Vuoi Eliminare la canzone {{object.titolo|capfirst}}?
    <br>
    <a style="font-size:30px;color:black;text-decoration:underline;" href="{%url 'gestione:listacanzoni' %}">Torna alla lista di canzoni</a>
{% endblock %}

{% load static %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p style="font-size:45px;text-align:center">L'AZIONE NON È ANNULLABILE</p>
        {{ form }}
        <br>
        <center><input style="font-size:45px" type="submit" value="Conferma"></center>

    </form>
    </center>
{% endblock %}

PyGenius/gestione/templates/gestione/contributo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Contributo eliminato{%endblock%}

{% block header1 %}
    <center>
        Vuoi Eliminare il contributo {{object.testo|capfirst}}?
    <br>
    <a style="font-size:30px;color:black;text-decoration:underline;" href="{%url 'gestione:listacanzoni' %}">Torna alla lista di canzoni</a>
{% endblock %}

{% load static %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p style="font-size:45px;text-align:center">L'AZIONE NON È ANNULLABILE</p>
        {{ form }}
        <br>
        <center><input style="font-size:45px" type="submit" value="Conferma"></center>

    </form>
    </center>
{% endblock %}

PyGenius/gestione/templates/gestione/creaalbum.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %} {{view.title}} {% endblock %}

{% block content %}

<center>
<div class="card d-flex justify-content-center " style="text-align:center;background-color:#2E1C2B;width:75%">
  <h5 class="card-header" style="background-color:#2E1C2B;color:#E4DFE2;height:70px">Inserisci i dati dell'album</h5>
  {% if request.GET.error == 'double' %}

    <h6 style="background-color:#2E1C2B;color:#dc3545;height:30px">
      <br>

      Esiste già un album con questo titolo e artista!
    </h6>
  {% endif %}
  <br>
  <div class="card-body" style="color:#E4DFE2">{% crispy form %}</div>



</div></center>
<br>


<br>

{% endblock %}

PyGenius/gestione/templates/gestione/creacanzone.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %} {{view.title}} {% endblock %}



{% block content %}

<center>
<div class="card d-flex justify-content-center " style="text-align:center;background-color:#2E1C2B;width:75%">
  <h5 class="card-header" style="background-color:#2E1C2B;color:#E4DFE2;height:70px">Inserisci i dati della canzone</h5>
  {% if request.GET.error == 'double' %}

    <h6 style="background-color:#2E1C2B;color:#dc3545;height:30px">
      <br>

      Esiste già una canzone con questo titolo e artista!
    </h6>
  {% endif %}
  <br>
  <div class="card-body" style="color:#E4DFE2">{% crispy form %}</div>



</div></center>
<br>


<br>

{% endblock %}

PyGenius/gestione/templates/gestione/creacontributo.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %} {{view.title}} {{view.editor}} {% endblock %}

{% block content %}

<center>
<div class="card d-flex justify-content-center " style="text-align:center;background-color:#2E1C2B;width:75%">
  <h5 class="card-header" style="background-color:#2E1C2B;color:#E4DFE2;height:70px">Inserisci i dati del contributo</h5>
  <br>
  <div class="card-body" style="color:#E4DFE2">{% crispy form %}</div>



</div></center>
<br>


<br>

{% endblock %}

PyGenius/gestione/templates/gestione/dettagliaalbum.html
{% extends 'base.html' %}

{% load static %}
{% load tags_gestione %}
{% block title %} {{object.visite}} {{object.autore}} ― {{object.titolo}}{% endblock %}


{% block content %}



<div hidden> {{object.p}}</div>




<div class="card d-flex" style="text-align:center;background-color:#E4DFE2; border: 2px solid #D9D3D0;border-radius: 5px;">



      <div class="card-header" style="font-size:45px"> <img style=" border: 2px solid #2E1C2B;border-radius: 10px;" src="{% static object.cover.url %}" width="200"  height="200">
          <div style="color:#4B1B39;padding:20px;text-align:center;"> {{object.titolo|capfirst}}
            <br>
           <p style="font-size:30px;color:#4B1B39"> <a style="color:#4B1b39" href="{% url 'gestione:listacanzoni' object.autore.pk %}">{{object.autore|capfirst}}</a></p>
          </div>
      </div>


    <div class="card-body" style="background-color:#E4DFE2;width:75;color:#4B1B39;text-align:center">



    </div>


</div>

  <br>
  <br>

    <center>

      {% for can in lista_canzoni %}
<div class="card d-flex" style="background-color:#E4DFE2;text-align:center">
    <div class="card-header">
           <br>
    <a class="card-body" style="color:#893168;font-size:25px" href="{% url 'gestione:listacanzoni' can.autore.pk %}">{{can.autore|capfirst}}</a> <a style="color:#893168;font-size:25px" href="{% url 'gestione:dettagliacanzone' can.pk %}"> {{can.titolo}}</a>


        </div>



</div>
<br>
{% endfor %}
 {% if user.is_authenticated %}
    </center>
  <br>
  {% if user.pk == object.autore.pk %}
    <center>
      <div class="card" style="width:200px;text-align:center;border:5px solid;border-color:#4A1942;border-radius:50px">
      <a style="color:#E4DFE2;background-color:#4A1942" href="{% url 'gestione:eliminaalbum' object.pk %}">
        Elimina Album
      </a>
    </div>
    </center>
  {% endif %}
  {% endif %}


{% endblock %}

PyGenius/gestione/templates/gestione/dettagliacanzone.html
{% extends 'base.html' %}

{% load static %}
{% load tags_gestione %}

{% block title %} {{object.visite}} {{object.autore}} ― {{object.titolo}}{% endblock %}


{% block content %}





{% if user.is_authenticated %}

<div hidden> {% visita object user.pk %} {{object.pop}}</div>

{% else %}



<div hidden> {% visita object guest %} {{object.pop}}</div>

{% endif %}

<div class="card d-flex" style="text-align:center;background-color:#E4DFE2; border: 2px solid #D9D3D0;border-radius: 5px;">



      <div class="card-header" style="font-size:45px"> <img style=" border: 2px solid #2E1C2B;border-radius: 10px;" src="{% static object.cover.url %}" width="200"  height="200">
          <div style="color:#4B1B39;padding:20px;text-align:center;"> {{object.titolo|capfirst}}
            <br>
           <p style="font-size:30px;color:#4B1B39">
               <a style="color:#4B1b39" href="{% url 'gestione:listacanzoni' object.autore.pk %}">{{object.autore|capfirst}}</a>

               {% if object.album != None %}
               <a style="color:#4B1b39" href="{% url 'gestione:dettagliaalbum' object.album.pk %}">{{object.album.titolo|capfirst}}</a>
               {% endif %}
               {{object.durata}}</p>
          </div>
      </div>


    <div class="card-body" style="background-color:#E4DFE2;width:75;color:#4B1B39;text-align:center">{{object.testo|linebreaksbr}}</div>


</div>

  <br>
  <br>

    <center>
        <script>

    function upvote() {

        }

</script>
      {% for contr in lista_contributi_star %}
<div class="card d-flex" style="background-color:#E4DFE2;text-align:center">
    <div class="card-header">
           <br>
    <a class="card-body" style="color:#893168;font-size:25px" href="{% url 'gestione:listacanzoni' contr.editor.pk %}">{{contr.editor|capfirst}}</a>



            {% if contr.pk|slugify == request.GET.upvote %}
                <div hidden>{{contr.upvote}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}


            {% if contr.pk|slugify == request.GET.downvote %}
                <div hidden>{{contr.downvote}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}

            {% if contr.pk|slugify == request.GET.star %}
                <div hidden>{{contr.star}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}


            <a href="{% url 'gestione:dettagliacanzone' object.pk %}?upvote={{contr.pk}}">
                <input type="button" style="text-align:center;border-radius:25px" value="⇧">
            </a>
            {{contr.upvotes}}


            <a href="{% url 'gestione:dettagliacanzone' object.pk %}?downvote={{contr.pk}}">
                <input type="button" style="text-align:center;border-radius:25px" value="⇩">
            </a>
        {% if user == object.autore %}
            {% if contr.ha_star != True %}


        <a href="{% url 'gestione:dettagliacanzone' object.pk %}?star={{contr.pk}}">
            <input type="button" value="🌟" ;style="text-align:center;border-radius:25px">  </input>
        </a>

        {% endif %}
        {% endif %}
         {% if contr.ha_star == True %}
        <a>🌟</a>
        {% endif %}


        </div>
            <center>
                <br>
          <p style="color:#4B1B39;text-align:center">
              {{contr.testo|capfirst}}
              <br>
          </p>


                </center>

   {% if user == contr.editor %}
        <center><a style="color:#E4DFE2;background-color:#4A1942;border-radius:10px" href="{% url 'gestione:eliminacontributo' contr.pk %}">
        Elimina Contributo
      </a> <br> <br></center>
    {% endif %}
</div>
<br>
{% endfor %}


        {% for contr in lista_contributi_non_star %}
<div class="card d-flex" style="background-color:#E4DFE2;text-align:center">
    <div class="card-header">
           <br>
    <a class="card-body" style="color:#893168;font-size:25px" href="{% url 'gestione:listacanzoni' contr.editor.pk %}">{{contr.editor|capfirst}}</a>



           {% if contr.pk|slugify == request.GET.upvote %}
                <div hidden>{{contr.upvote}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}


            {% if contr.pk|slugify == request.GET.downvote %}
                <div hidden>{{contr.downvote}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}

            {% if contr.pk|slugify == request.GET.star %}
                <div hidden>{{contr.star}}</div>
                <meta http-equiv="REFRESH" content="0;url={% url 'gestione:dettagliacanzone' object.pk %}">
            {% endif %}


            <a href="{% url 'gestione:dettagliacanzone' object.pk %}?upvote={{contr.pk}}">
                <input type="button" style="text-align:center;border-radius:25px" value="⇧">
            </a>
            {{contr.upvotes}}


            <a href="{% url 'gestione:dettagliacanzone' object.pk %}?downvote={{contr.pk}}">
                <input type="button" style="text-align:center;border-radius:25px" value="⇩">
            </a>
        {% if user == object.autore %}
        <a href="{% url 'gestione:dettagliacanzone' object.pk %}?star={{contr.pk}}">
            <input type="button" value="🌟" ;style="text-align:center;border-radius:25px">  </input>
        </a>

        {% endif %}


        </div>
            <center>
                <br>
          <p style="color:#4B1B39;text-align:center">
              {{contr.testo|capfirst}}
              <br>
          </p>


                </center>
    {% if user == contr.editor %}
        <center><a style="color:#E4DFE2;background-color:#4A1942;border-radius:10px" href="{% url 'gestione:eliminacontributo' contr.pk %}">
         <br>Elimina Contributo<br>
      </a> <br> <br></center>
    {% endif %}


</div>
<br>
{% endfor %}







 {% if user.is_authenticated %}
      <div class="card" style="width:200px;text-align:center;border:5px solid;border-color:#4A1942;border-radius:50px">

      <a style="color:#E4DFE2;background-color:#4A1942" href="{% url 'gestione:creacontributo' object.pk %}">
        Crea Contributo
      </a>
      </div>

    </center>
  <br>
  {% if user.pk == object.autore.pk %}
    <center>
      <div class="card" style="width:200px;text-align:center;border:5px solid;border-color:#4A1942;border-radius:50px">
      <a style="color:#E4DFE2;background-color:#4A1942" href="{% url 'gestione:eliminacanzone' object.pk %}">
        Elimina Canzone
      </a>
    </div>
    </center>
  {% endif %}
  {% endif %}


{% endblock %}

PyGenius/gestione/templates/gestione/listaalbum.html
{% extends 'base.html' %}


{% block header1 %}{{title}}{% endblock %}

{% block title %} {{title}}{% endblock %}

{% load static %}

{% block content %}

{% if request.GET.albumeliminato  %}

<div id="info1" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Eliminato {{request.GET.albumeliminato}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> La procedura di eliminazione dell'album {{request.GET.albumeliminato}} è andata a buon fine </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $("#info1").modal('show');
  });
</script>

{% endif %}




{% for can in object_list %}
<div class="card d-flex" style="background-color:#3C1B37;border: 4px solid #893168;border-radius:10px;text-align:center">

  <h5 class="card-header" style="color:#E4DFE2;font-size:40px">
      <br>
        <img style="border: 2px solid #893168;border-radius: 25px;" src="{% static can.cover.url %}" width="150"  height="150">
            <br>
            <br>
            <center>
          <a style="color:#E4DFE2;text-align:center" href="{% url 'gestione:dettagliaalbum' can.pk %}">
              {{can.titolo|capfirst}}
              <br>
              <a class="card-body" style="color:#E4DFE2;font-size:20px" href="{% url 'gestione:listacanzoni' can.autore.pk %}">{{can.autore|capfirst}}</a>

          </a>
                </center>

  </h5>
</div>
<br>
{% endfor %}

{% endblock %}