PyGenius/PyGenius/urls.py
from django.contrib import admin
from .initcmds import init_db
from django.urls import path, include, re_path
from .views import *
from gestione.views import ListaCanzoni

urlpatterns = [
    re_path(r'^$|^\/$|^home\/$', ListaCanzoni.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('gestione/', include('gestione.urls')),
]
#init_db()

PyGenius/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', CreaUtenteEditor.as_view(), name='register'),
    path('register-artist/', CreaUtenteArtista.as_view(), name='register-artist')
]

PyGenius/gestione/urls.py
from django.urls import path, include, re_path
from .views import *

app_name='gestione'

urlpatterns = [
    path('creacanzone/', CreaCanzone.as_view(), name='creacanzone'),
    path('listacanzoni/', ListaCanzoni.as_view(), name='listacanzoni'),
    path('listacanzoni/<pk>/', ListaCanzoniArtista.as_view(), name='listacanzoni'),
    path('dettagliacanzone/<pk>/', DettagliaCanzone.as_view(), name='dettagliacanzone'),
    path('eliminacanzone/<pk>/', EliminaCanzone.as_view(), name='eliminacanzone'),
    path('creacontributo/<pk>/', CreaContributo.as_view(), name='creacontributo'),
    path('eliminacontributo/<pk>/', EliminaContributo.as_view(), name='eliminacontributo'),
    path('creaalbum/', CreaAlbum.as_view(), name='creaalbum'),
    path('listaalbum/', ListaAlbum.as_view(), name='listaalbum'),
    path('dettaglialbum/<pk>/', DettagliaAlbum.as_view(), name='dettagliaalbum'),
    path('eliminaalbum/<pk>/', EliminaAlbum.as_view(), name='eliminaalbum'),
    path('ricerca/', RisultatiRicerca, name='ricerca'),
]

PyGenius/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
  {% endblock %}
  {% load crispy_forms_tags %}

</head>

{% load tags_gestione %}
<title  >♫ PyGenius ♫ {% block title %} {% endblock %}</title>

<style>
    .navbar-custom {
        background-color:#2E1C2B;
    }
    .navbar-custom .navbar-link-container {
      float:left;
      width:auto;
    }
    .navbar-custom .navbar-search-container {
        float:right;
        width:auto;
        color: black
    }



    .searchbar {
        background-color:#3C1B37;
        color:#E4DFE2;
        border:1px solid #E4DFE2;
        border-radius: 5px

    }

    .search-button {
        background-color:#E4DFE2;
        border: 2px solid E4DFE2;
    }

    .navbar-custom .navbar-brand{
        color: #893168;
    }

    .navbar-custom .nav-link {
        background-color:#2E1C2B;
        color:#E4DFE2;
        float:left;

    }
</style>


<body style="background-color:#E4DFE2;font-family:courier new" >



{% if user.is_authenticated and "ok" in request.GET.login  %}

<div id="info1" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Welcome {{user.username}} </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> La procedura di login è andata a buon fine </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $("#info1").modal('show');
  });
</script>

{% endif %}


<nav class="navbar navbar-custom" navbar>
    {% block navbar %}
    <div class="navbar navbar-link-containter">
        <a class="navbar-brand" href="{% url 'home' %}">PyGenius</a>

        <a class="nav-link" href="{% url 'gestione:listacanzoni' %}">Lista Canzoni</a>
         <a class="nav-link" href="{% url 'gestione:listaalbum' %}">Lista Albums</a>
        {% if user.is_authenticated %}
        {% if user|has_group:"Artisti" %}

          <a class="nav-link" href="{% url 'gestione:creacanzone' %}">Aggiungi Canzone</a>

          <a class="nav-link" href="{% url 'gestione:creaalbum' %}">Aggiungi Album</a>
        {% endif %}

          <a class="nav-link" href='{% url "accounts:logout" %}'>{{user.username}} Logout</a>
        {% else %}
          <a class="nav-link" href='{% url "accounts:login" %}'>Login</a>
        {% endif %}
</div>
    <div class="navbar navbar-search-container">







        <form  id="search" method="GET" action="{% url 'gestione:ricerca'%}">
             <select name="model">
                <option value="Canzoni">Canzoni</option>
                <option value="Album" selected>Album</option>
                <option value="Artisti">Artisti</option>

            </select>
            <input class="searchbar" type="text" placeholder="Cerca..." name="q">
        <input class="search-button"  type="submit" value="🔍">
        </form>
    </div>
  {% endblock %}


</nav>

<h1 class="jumbotron text-center" style="background-color:#E4DFE2;font-family:courier new;height:150px">
  {% block header1 %}

{% endblock %}
</h1>


{% block allert %}
          {% if request.GET.loggedout != None %}

<div id="info" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Arrivederci</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> La procedura di logout è andata a buon fine </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $("#info").modal('show');
  });
</script>

          {% endif %}
{% endblock %}


  <div class="container" style='margin-top:30px'>

      <div class="col-sm-22">




        {% block content %}


        <h2>TITLE HEADING</h2>
        <h5>Title description, Dec 7, 2017</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Some text..</p>
        <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        {% endblock %}
        <br>

      </div>
    </div>

  </body>
  </html>

PyGenius/templates/home.html
{% extends 'base.html' %}

{% block title %} HomePage {% endblock %}

{% block header1 %}HomePage{% endblock %}

{% block content %}

{% endblock %}